#!/usr/bin/env python

import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-s", "--start-address", help="Beginning memory address to carve")
parser.add_argument("-e", "--end-address", help="End memory address to carve")
parser.add_argument("file", help="Path to the file")
parser.add_argument("--hex", action="store_true", help="Format output as ASCII hex")

if __name__ == "__main__":
    args = parser.parse_args()
    start_address   = int(args.start_address, 16)
    end_address     = int(args.end_address, 16)
    num_bytes       = end_address - start_address
    try:
        f = open(args.file, "r")
    except:
        print "[+] Cannot open file."
        sys.exit(-1)
    data = f.seek(start_address)
    data = f.read(num_bytes)
    f.close()
    if args.hex:
        print data.encode("hex")
    else:
        sys.stdout.write(data)
